### ISSUE TITLE
Catch ValueError in trade

### ISSUE THREAD

**Issue by 4Kaylum** [Voxel-Fox-Ltd/Flower#64]
The bot hit a `Command raised an exception: ValueError: list.remove(x): x not in list` error while running the `f.trade <@!758047478078767195>` command.
```python
Traceback (most recent call last):
  File "/home/kae/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/kae/Flower/./cogs/plant_shop_commands.py", line 632, in tradeplant
    pending_response.remove(payload.user.id)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kae/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/kae/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/kae/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: list.remove(x): x not in list
```

**Comment by 4Kaylum** [comment]
No longer an issue with rewrite.
